export const sample = [
    {
      boundingBox: "823,79,203,14",
      medicine: {
        item: {
          tenThuoc: "BS ton",
          soDangKy: "VD-29932-18",
          thongTinDangKyThuoc: {
            ngayCapSoDangKy: "2018-03-27T00:00:00+07:00",
            ngayGiaHanSoDangKy: null,
            ngayHetHanSoDangKy: null,
            soQuyetDinh: "181/QÐ-QLD",
            urlSoQuyetDinh: null,
            dotCap: null,
          },
          thongTinThuocCoBan: {
            hoatChatHamLuong: null,
            hoatChatChinh:
              "Mỗi 1,5 g bột pha hỗn dịch chứa: Sulfamethoxazol 200mg; Trimethoprim 40mg",
            hoatChatChinhId: null,
            hamLuong: "200mg, 40mg",
            dangBaoChe: "Bột pha hỗn dịch uống",
            dangBaoCheId: null,
            dongGoi: "Hộp 20 gói x 1,5g",
            dongGoiJson: null,
            maDuongDung: null,
            tenDuongDung: null,
            tieuChuan: "TCCS",
            tieuChuanId: null,
            tuoiTho: "36 tháng",
            loaiThuoc: null,
            loaiThuocId: null,
            nhomThuoc: null,
            nhomThuocId: null,
          },
          congTySanXuat: {
            tenCongTySanXuat: "Công ty cổ phần dược TW Mediplantex",
            diaChiSanXuat:
              "Nhà máy dược phẩm số 2: Trung Hậu, Tiền Phong, Mê Linh, Hà Nội",
            nuocSanXuat: "Việt Nam",
            nuocSanXuatId: null,
          },
          phanLoaiThuocEnum: 1,
          ghiChu: null,
          isActive: true,
          id: "22717",
        },
        refIndex: 22716,
      },
    },
    {
      boundingBox: "36,520,401,30",
      medicine: {
        item: {
          tenThuoc: "Gliclazid",
          soDangKy: "VD-14212-11",
          thongTinDangKyThuoc: {
            ngayCapSoDangKy: "2011-03-23T00:00:00+07:00",
            ngayGiaHanSoDangKy: null,
            ngayHetHanSoDangKy: null,
            soQuyetDinh: "81/QĐ-QLD",
            urlSoQuyetDinh: null,
            dotCap: null,
          },
          thongTinThuocCoBan: {
            hoatChatHamLuong: null,
            hoatChatChinh: "Gliclazid 80mg",
            hoatChatChinhId: null,
            hamLuong: "",
            dangBaoChe: "",
            dangBaoCheId: null,
            dongGoi: "hộp 6 vỉ x 10 viên nén",
            dongGoiJson: null,
            maDuongDung: null,
            tenDuongDung: null,
            tieuChuan: "TCCS",
            tieuChuanId: null,
            tuoiTho: "24 tháng",
            loaiThuoc: null,
            loaiThuocId: null,
            nhomThuoc: null,
            nhomThuocId: null,
          },
          congTySanXuat: {
            tenCongTySanXuat: "Công ty cổ phần Dược phẩm 3/2..",
            diaChiSanXuat:
              "Số 930 C2, Đường C, KCN Cát Lái, P. Thạnh Mỹ Lợi, Q2, TP. Hồ Chí Minh",
            nuocSanXuat: "Việt Nam",
            nuocSanXuatId: null,
          },
          phanLoaiThuocEnum: 1,
          ghiChu: null,
          isActive: true,
          id: "5937",
        },
        refIndex: 5936,
      },
    },
    {
      boundingBox: "29,624,450,35",
      medicine: {
        item: {
          tenThuoc: "Pregabalin Sandoz",
          soDangKy: "VN-19190-15",
          thongTinDangKyThuoc: {
            ngayCapSoDangKy: "2015-10-06T00:00:00+07:00",
            ngayGiaHanSoDangKy: null,
            ngayHetHanSoDangKy: null,
            soQuyetDinh: "548/QÐ-QLD",
            urlSoQuyetDinh: null,
            dotCap: null,
          },
          thongTinThuocCoBan: {
            hoatChatHamLuong: null,
            hoatChatChinh: "Pregabalin 150mg",
            hoatChatChinhId: null,
            hamLuong: null,
            dangBaoChe: "Viên nang cứng",
            dangBaoCheId: 3,
            dongGoi: "Hộp 4 vỉ x 7 viên",
            dongGoiJson: null,
            maDuongDung: null,
            tenDuongDung: null,
            tieuChuan: "NSX",
            tieuChuanId: 112,
            tuoiTho: "24 tháng",
            loaiThuoc: null,
            loaiThuocId: null,
            nhomThuoc: null,
            nhomThuocId: null,
          },
          congTySanXuat: {
            tenCongTySanXuat: "Hexal AG",
            diaChiSanXuat: "Industriestrasse 25, D-83607 Holzkirchen",
            nuocSanXuat: "Đức",
            nuocSanXuatId: 1583,
          },
          phanLoaiThuocEnum: 2,
          ghiChu: null,
          isActive: true,
          id: "34039",
        },
        refIndex: 34038,
      },
    },
    {
      boundingBox: "30,735,319,31",
      medicine: {
        item: {
          tenThuoc: "Valsartan-MV",
          soDangKy: "VD-32469-19",
          thongTinDangKyThuoc: {
            ngayCapSoDangKy: "2019-02-27T00:00:00+07:00",
            ngayGiaHanSoDangKy: null,
            ngayHetHanSoDangKy: null,
            soQuyetDinh: "108/QÐ-QLD",
            urlSoQuyetDinh: null,
            dotCap: "Đợt 164",
          },
          thongTinThuocCoBan: {
            hoatChatHamLuong: null,
            hoatChatChinh: "Valsartan 80mg",
            hoatChatChinhId: null,
            hamLuong: "80mg",
            dangBaoChe: "Viên nén bao phim",
            dangBaoCheId: null,
            dongGoi: "Hộp 3 vỉ x 10 viên",
            dongGoiJson: null,
            maDuongDung: null,
            tenDuongDung: null,
            tieuChuan: "TCCS",
            tieuChuanId: null,
            tuoiTho: "36 tháng",
            loaiThuoc: null,
            loaiThuocId: null,
            nhomThuoc: null,
            nhomThuocId: null,
          },
          congTySanXuat: {
            tenCongTySanXuat: "Công ty TNHH US Pharma USA",
            diaChiSanXuat:
              "Lô B1-10, Đường D2, KCN Tây Bắc Củ Chi, TP. Hồ Chí Minh",
            nuocSanXuat: "Việt Nam",
            nuocSanXuatId: null,
          },
          phanLoaiThuocEnum: 1,
          ghiChu: null,
          isActive: true,
          id: "37937",
        },
        refIndex: 37928,
      },
    },
    {
      boundingBox: "30,842,371,35",
      medicine: {
        item: {
          tenThuoc: "Clopidogrel",
          soDangKy: "VD-21412-14",
          thongTinDangKyThuoc: {
            ngayCapSoDangKy: "2014-08-12T00:00:00+07:00",
            ngayGiaHanSoDangKy: null,
            ngayHetHanSoDangKy: null,
            soQuyetDinh: "437/QÐ-QLD",
            urlSoQuyetDinh: null,
            dotCap: null,
          },
          thongTinThuocCoBan: {
            hoatChatHamLuong: null,
            hoatChatChinh: "Clopidogrel (dưới dạng Clopidogrel bisulfat) 75mg",
            hoatChatChinhId: null,
            hamLuong: null,
            dangBaoChe: "Viên nén bao phim",
            dangBaoCheId: null,
            dongGoi:
              "Hộp 3 vỉ, 5 vỉ, 10 vỉ, 50 vỉ x 10 viên, hộp 5 vỉ, 10 vỉ, 15 vỉ, 20 vỉ x 6 viên, hộp 3 vỉ, 5 vỉ, 10 vỉ, 50 vỉ x 20 viên, chai 50 viên, 100 viên, 200 viên, 500 viên",
            dongGoiJson: null,
            maDuongDung: null,
            tenDuongDung: null,
            tieuChuan: "TCCS",
            tieuChuanId: null,
            tuoiTho: "36 tháng",
            loaiThuoc: null,
            loaiThuocId: null,
            nhomThuoc: null,
            nhomThuocId: null,
          },
          congTySanXuat: {
            tenCongTySanXuat: "Công ty cổ phần dược Vacopharm",
            diaChiSanXuat:
              "Km 1954, quốc lộ 1A, P. Tân Khánh, TP. Tân An, Long An",
            nuocSanXuat: "Việt Nam",
            nuocSanXuatId: null,
          },
          phanLoaiThuocEnum: 1,
          ghiChu: null,
          isActive: true,
          id: "3457",
        },
        refIndex: 3456,
      },
    },
    {
      boundingBox: "34,948,348,31",
      medicine: {
        item: {
          tenThuoc: "Metformin",
          soDangKy: "VD-31992-19",
          thongTinDangKyThuoc: {
            ngayCapSoDangKy: "2019-02-27T00:00:00+07:00",
            ngayGiaHanSoDangKy: null,
            ngayHetHanSoDangKy: null,
            soQuyetDinh: "108/QÐ-QLD",
            urlSoQuyetDinh: null,
            dotCap: "Đợt 164",
          },
          thongTinThuocCoBan: {
            hoatChatHamLuong: null,
            hoatChatChinh: "Metformin HCl 1000mg",
            hoatChatChinhId: null,
            hamLuong: "1000mg",
            dangBaoChe: "Viên bao phim",
            dangBaoCheId: null,
            dongGoi: "Vỉ 10 viên; hộp 3 vỉ, 5vỉ, 10 vỉ. Chai 50 viên, 100 viên",
            dongGoiJson: null,
            maDuongDung: null,
            tenDuongDung: null,
            tieuChuan: "TCCS",
            tieuChuanId: null,
            tuoiTho: "36 tháng",
            loaiThuoc: null,
            loaiThuocId: null,
            nhomThuoc: null,
            nhomThuocId: null,
          },
          congTySanXuat: {
            tenCongTySanXuat: "Công ty cổ phần dược phẩm TV. Pharm",
            diaChiSanXuat:
              "27 Điện Biên Phủ, phường 9, TP. Trà Vinh, tỉnh Trà Vinh",
            nuocSanXuat: "Việt Nam",
            nuocSanXuatId: null,
          },
          phanLoaiThuocEnum: 1,
          ghiChu: null,
          isActive: true,
          id: "37912",
        },
        refIndex: 37903,
      },
    },
  ];